api_version: 3
name: example_project
description: NVIDIA FLARE sample project yaml file

client_components: &cln_comps
  resource_manager:
    path: nvflare.app_common.resource_managers.list_resource_manager.ListResourceManager
    args:
      resources:
        gpu: [0, 1, 2, 3]
  resource_consumer:
    path: nvflare.app_common.resource_consumers.gpu_resource_consumer.GPUResourceConsumer
    args:
      gpu_resource_key: gpu

server_components: &svr_comps
  job_scheduler:
    path: nvflare.app_common.job_schedulers.job_scheduler.DefaultJobScheduler
    args:
      max_jobs: 1
  job_manager:
    path: nvflare.apis.impl.job_def_manager.SimpleJobDefManager
    args:
      uri_root: /persist/jobs-storage
      job_store_id: job_store
  job_store:
    path: nvflare.app_common.storages.filesystem_storage.FilesystemStorage

participants:
  - name: overseer
    type: overseer
    org: nvidia
    protocol: https
    api_root: /api/v1
    port: 8443
  - name: server1
    type: server
    org: nvidia
    fed_learn_port: 8002
    admin_port: 8003
    enable_byoc: true
    components:
      <<: *svr_comps
  - name: server2
    type: server
    org: nvidia
    fed_learn_port: 8102
    admin_port: 8103
    enable_byoc: true
    components:
      <<: *svr_comps
  - name: site-1
    type: client
    org: nvidia
    enable_byoc: true
    components:
      <<: *cln_comps
  - name: site-2
    type: client
    org: nvidia
    enable_byoc: false
    components:
      <<: *cln_comps
      resource_manager:
        path: nvflare.app_common.resource_managers.list_resource_manager.ListResourceManager
        args:
          resources:
            gpu: [0, 1]
  - name: admin@nvidia.com
    type: admin
    org: nvidia
    roles:
      - super

builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file: master_template.yml
  - path: nvflare.lighter.impl.template.TemplateBuilder
  - path: nvflare.lighter.impl.helm_chart.HelmChartBuilder
    args:
      docker_image: localhost:32000/nvfl-min:0.0.1
  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      config_folder: config

      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        overseer_exists: false
        args:
          sp_end_point: server1:8002:8003

      snapshot_persistor:
        path: nvflare.app_common.state_persistors.storage_state_persistor.StorageStatePersistor
        args:
          uri_root: /
          storage:
            path: nvflare.app_common.storages.filesystem_storage.FilesystemStorage
            args:
              root_dir: /persist/snapshot-storage
              uri_root: /

  - path: nvflare.lighter.impl.auth_policy.AuthPolicyBuilder
    args:
      orgs:
        nvidia:
          - relaxed
      roles:
        super: super user of system
      groups:
        relaxed:
          desc: org group with relaxed policies
          rules:
            allow_byoc: true
            allow_custom_datalist: true
      disabled: false
  - path: nvflare.lighter.impl.cert.CertBuilder
  - path: nvflare.lighter.impl.signature.SignatureBuilder
